baseURL = "https://orangecrab-fpga.github.io/orangecrab-hardware"
languageCode = "en-us"
title = "OrangeCrab"
theme = "book"
themesDir = "./themes"

enableGitInfo = true
disableKinds = ['taxonomy']


[params]
  BookTheme = 'light'
  BookToC = true
  BookMenuBundle = '/menu'

  BookSection = 'docs'
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true


[params.footer]
	copyright = "[gregdavill](https://twitter.com/gregdavill)"
	show_powered_by = true

[markup.goldmark.renderer]
    unsafe= true
    hardWraps = true
  
[markup.highlight]
    codeFences = true
    pygmentscodefences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "manni"
